"""Final README polish for the urban drainage toolkit.

Run from the repository root:

    python scripts/polish_readme_outputs_and_ci.py

This script fixes the remaining README consistency issues:

1. Keeps `report_summary.png` under the QA/QC report output, not the map output.
2. Adds `status_rules.py` to the source tree shown in the README.
3. Updates `reporting.py` wording to mention report plots.
4. Keeps the map section focused on the dashboard HTML and point CSV.
"""

from pathlib import Path

README = Path("README.md")


def polish_qaqc_output_block(text: str) -> str:
    old_a = """Expected output:

```text
examples/outputs/demo/report.html
examples/outputs/demo/report/summary.csv
```"""

    old_b = """Expected output:

```text
examples/outputs/demo/report/report.html
examples/outputs/demo/report/summary.csv
```"""

    new = """Expected output:

```text
examples/outputs/demo/report/
├── report.html
├── report_summary.png
├── summary.csv
└── file_inventory.csv
```"""

    text = text.replace(old_a, new)
    text = text.replace(old_b, new)
    return text


def polish_map_output_block(text: str) -> str:
    wrong = """Expected output:

```text
examples/outputs/synthetic_map/
├── synthetic_monitoring_points.csv
├── synthetic_monitoring_points.html
└── report_summary.png  # generated by the QA/QC report demo
```"""

    correct = """Expected output:

```text
examples/outputs/synthetic_map/
├── synthetic_monitoring_points.csv
└── synthetic_monitoring_points.html
```"""

    text = text.replace(wrong, correct)
    text = text.replace("### 3. Synthetic monitoring-point map", "### 3. Synthetic monitoring dashboard map")
    text = text.replace("## Synthetic map example", "## Synthetic dashboard map example")

    text = text.replace(
        "├── synthetic_monitoring_points.html\n└── report_summary.png  # generated by the QA/QC report demo",
        "└── synthetic_monitoring_points.html",
    )
    return text


def polish_source_tree(text: str) -> str:
    old = """src/urban_drainage_sensor_toolkit/
├── audit.py          # private-folder audit helpers
├── cli.py            # command-line interface
├── core.py           # core cleaning and QA/QC functions
├── io_utils.py       # input/output helpers
├── maps.py           # public-safe synthetic map generation
├── reporting.py      # HTML/CSV report generation
├── synthetic.py      # synthetic telemetry generation
└── ml/               # optional applied-AI anomaly screening"""

    new = """src/urban_drainage_sensor_toolkit/
├── audit.py          # private-folder audit helpers
├── cli.py            # command-line interface
├── core.py           # core cleaning and QA/QC functions
├── io_utils.py       # input/output helpers
├── maps.py           # public-safe synthetic map generation
├── reporting.py      # HTML/CSV report and plot generation
├── status_rules.py   # stale-data, battery, flatline, level and flow checks
├── synthetic.py      # synthetic telemetry generation
└── ml/               # optional applied-AI anomaly screening"""

    text = text.replace(old, new)
    text = text.replace(
        "├── reporting.py      # HTML/CSV report generation\n├── synthetic.py",
        "├── reporting.py      # HTML/CSV report and plot generation\n├── status_rules.py   # stale-data, battery, flatline, level and flow checks\n├── synthetic.py",
    )
    return text


def polish_description_table(text: str) -> str:
    text = text.replace(
        "| Automated reporting | Static HTML and CSV summaries from synthetic telemetry |",
        "| Automated reporting | Static HTML, CSV summaries, and report-summary plots from synthetic telemetry |",
    )
    text = text.replace(
        "| Synthetic map output | Fictional monitoring-point map with synthetic coordinates only |",
        "| Synthetic map output | Dashboard-style monitoring map with fictional points and synthetic coordinates only |",
    )
    return text


def main() -> None:
    text = README.read_text(encoding="utf-8")
    text = polish_description_table(text)
    text = polish_qaqc_output_block(text)
    text = polish_map_output_block(text)
    text = polish_source_tree(text)
    README.write_text(text, encoding="utf-8")
    print("Polished README output sections and source tree.")


if __name__ == "__main__":
    main()
